version: '3.8'

services:
  # ------------------
  # Laravel + MySQL
  # ------------------
  laravel-klasea:
    image: php:8.2-fpm-bullseye
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel-klasea
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8080:8080"
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8080"
    networks:
      - app-network

# Odoo Zerbitzua
  odoo:
    image: odoo:17.0
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - odoo_data:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons
    networks:
      - app-network
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    networks:
      - app-network

# ------------------
# Bolumenak eta sareak
# ------------------
volumes:
  mysql_data:
  postgres_data:
  # Odoo fitxategien bolumen berria
  odoo_data: 
  redis_data:

networks:
  app-network:
    driver: bridge